// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvaPub.Infrastructure.Data;

#nullable disable

namespace ProvaPub.Infrastructure.Data.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20250818203906_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvaPub.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 505, DateTimeKind.Utc).AddTicks(3120),
                            Name = "Emmett Breitenberg"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 508, DateTimeKind.Utc).AddTicks(4450),
                            Name = "Gilbert Kunze"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 511, DateTimeKind.Utc).AddTicks(4096),
                            Name = "Jean Thompson"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 514, DateTimeKind.Utc).AddTicks(2571),
                            Name = "Boyd Weber"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 517, DateTimeKind.Utc).AddTicks(1305),
                            Name = "Regina Rosenbaum"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 520, DateTimeKind.Utc).AddTicks(3193),
                            Name = "Julio Haag"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 523, DateTimeKind.Utc).AddTicks(2243),
                            Name = "Conrad King"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 526, DateTimeKind.Utc).AddTicks(1304),
                            Name = "Lester Rippin"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 537, DateTimeKind.Utc).AddTicks(5951),
                            Name = "Shari Thompson"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 539, DateTimeKind.Utc).AddTicks(3832),
                            Name = "Herman Howell"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 541, DateTimeKind.Utc).AddTicks(15),
                            Name = "Alberto Wunsch"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 542, DateTimeKind.Utc).AddTicks(6261),
                            Name = "Josephine Zemlak"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 544, DateTimeKind.Utc).AddTicks(2588),
                            Name = "Sophia Williamson"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 545, DateTimeKind.Utc).AddTicks(8859),
                            Name = "Herbert Hoeger"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 547, DateTimeKind.Utc).AddTicks(4772),
                            Name = "Charlene Hettinger"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 549, DateTimeKind.Utc).AddTicks(1164),
                            Name = "Noel Koelpin"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 550, DateTimeKind.Utc).AddTicks(7723),
                            Name = "Leon Mayert"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 552, DateTimeKind.Utc).AddTicks(3580),
                            Name = "Charlotte Kihn"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 553, DateTimeKind.Utc).AddTicks(9709),
                            Name = "Ross Mertz"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 8, 18, 20, 39, 6, 555, DateTimeKind.Utc).AddTicks(5774),
                            Name = "Colleen Walker"
                        });
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Handmade Frozen Pants"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Refined Metal Mouse"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ergonomic Soft Computer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Handmade Cotton Shoes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Generic Metal Computer"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Handcrafted Wooden Towels"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Awesome Concrete Soap"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Tasty Rubber Towels"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Unbranded Frozen Computer"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gorgeous Wooden Towels"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Awesome Metal Cheese"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Awesome Granite Keyboard"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Awesome Frozen Mouse"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Handmade Metal Mouse"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Refined Wooden Pants"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Generic Rubber Pizza"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Intelligent Concrete Mouse"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Tasty Plastic Cheese"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tasty Concrete Mouse"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ergonomic Fresh Chicken"
                        });
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.RandomNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.Order", b =>
                {
                    b.HasOne("ProvaPub.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ProvaPub.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
